"""Policy loader and Bean selection for the Coffee Core Router.

Loads router/config/routing_policy.yaml (generated by tools/generate_policy.py
- never hand-edited) and selects a primary/fallback Bean per classified
task_type. Every routing decision records which policy entry justified it
(Requirement 4).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

from router.app.aliases import BeanRegistry

logger = logging.getLogger(__name__)

DEFAULT_ROUTING_POLICY_PATH = Path(__file__).resolve().parent.parent / "config" / "routing_policy.yaml"


class RoutingError(Exception):
    """Raised when a route cannot be resolved to an available Bean."""


class NoVisionBeanError(RoutingError):
    """Raised when a request needs a vision-capable Bean (an image was
    attached) but no Bean in beans.yaml has capabilities.vision: true.
    A distinct subclass so router/app/main.py can catch it specifically
    and emit error_type="no_vision_bean_available" (see docs/design/
    attachments-design.md Section 6.2) rather than a generic routing
    failure."""


class NoToolCallingBeanError(RoutingError):
    """Raised when a request needs a tool-calling-capable Bean (web
    search via `use_web`, or a /v1/chat/completions client's own `tools`
    array) but no Bean in beans.yaml has capabilities.tool_calling: true.
    A distinct subclass, mirroring NoVisionBeanError, so main.py can emit
    error_type="no_web_search_bean_available" rather than a generic
    routing failure. See docs/design/web-search-design.md."""


@dataclass(frozen=True)
class RouteDecision:
    task_type: str
    bean_alias: str
    fallback_bean_alias: Optional[str]
    premium_bean_alias: Optional[str]
    policy_entry: str
    policy_status: str
    est_cost_usd: Optional[float]
    # Added in Brew 38 (contract v1.2): why routing deviated from the
    # plain policy/manual pick, e.g. a vision constraint. None in the
    # normal, unconstrained case.
    constraint_reason: Optional[str] = None


class RoutingPolicy:
    def __init__(self, policy_data: Dict[str, Any], bean_registry: BeanRegistry):
        self._policy_data = policy_data
        self._bean_registry = bean_registry

    @classmethod
    def from_yaml(
        cls,
        path: Path = DEFAULT_ROUTING_POLICY_PATH,
        bean_registry: Optional[BeanRegistry] = None,
    ) -> "RoutingPolicy":
        with open(path, "r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        return cls(data, bean_registry or BeanRegistry.from_yaml())

    def entry_for_task_type(self, task_type: str) -> Dict[str, Any]:
        task_types = self._policy_data.get("task_types", {})
        entry = task_types.get(task_type)
        if entry is None:
            # Unknown task_type (e.g. classifier returned something the
            # policy has never seen): treat exactly like "default" rather
            # than raising, matching Requirement 4's stated fallback
            # behavior for thin/missing evidence.
            return {
                "status": "default",
                "primary_bean_alias": self._house_blend_default_alias(),
                "fallback_bean_alias": None,
                "premium_bean_alias": None,
                "evidence": [],
                "reason": f"Unknown task_type={task_type!r}; no policy entry exists.",
            }
        return entry

    def _house_blend_default_alias(self) -> str:
        default_bean = self._bean_registry.by_role("default")
        if default_bean is None:
            raise RoutingError("No default Bean is configured in beans.yaml.")
        return default_bean.alias

    def select_route(
        self,
        task_type: str,
        needs_vision: bool = False,
        *,
        needs_tool_calling: bool = False,
        preferred_tool_calling_bean_alias: Optional[str] = None,
        tokens_in: int = 0,
        assumed_output_tokens: int = 0,
    ) -> RouteDecision:
        entry = self.entry_for_task_type(task_type)
        primary_alias = entry.get("primary_bean_alias") or self._house_blend_default_alias()
        primary_bean = self._bean_registry.by_alias(primary_alias)

        if not primary_bean.is_available:
            # Never silently substitute a different role for an unavailable
            # Bean (Coffee Constitution Article 1: "must never represent
            # unverified output as certain fact" extends to routing
            # honesty). Fall back to the configured House Blend default.
            fallback_default_alias = self._house_blend_default_alias()
            primary_bean = self._bean_registry.by_alias(fallback_default_alias)
            primary_alias = fallback_default_alias

        constraint_reason = None
        if needs_vision and not primary_bean.vision:
            vision_bean = self._bean_registry.default_vision_bean()
            if vision_bean is None:
                # No vision-capable Bean exists anywhere (Brew 38 - see
                # docs/design/attachments-design.md Section 2, Gap 1: this
                # is every real request today). Never silently proceed
                # without the image or crash - the caller (main.py) turns
                # this into a clear `error` event.
                raise NoVisionBeanError(
                    "This request needs a vision-capable Bean, but none is "
                    "configured in beans.yaml."
                )
            constraint_reason = (
                f"needs_vision: escalated from {primary_alias} to {vision_bean.alias}"
            )
            primary_bean = vision_bean
            primary_alias = vision_bean.alias

        # Fires either when the primary Bean can't do tools at all (the
        # original escalation case), or when a preference was explicitly
        # given - the second clause is the fix for a real routing defect
        # (found during the free-Bean tool-calling verification Brew): the
        # old `needs_tool_calling and not primary_bean.tool_calling` guard
        # conflated "the primary Bean can technically do tools" with "the
        # primary Bean is the right Bean for this tools request" - the
        # instant any primary/default Bean's own tool_calling flag turned
        # true, this branch stopped firing at all, and
        # preferred_tool_calling_bean_alias (e.g. settings.yaml's
        # preferred_web_search_bean_alias="Kimi K2") was silently never
        # consulted, moving use_web traffic to whatever the primary Bean
        # happened to be with no test failing anywhere. An explicit
        # preference must always at least be checked.
        if needs_tool_calling and (
            not primary_bean.tool_calling or preferred_tool_calling_bean_alias is not None
        ):
            # web-search Brew: escalate to the cheapest capable Bean (see
            # BeanRegistry.capable_bean()) rather than a fixed role - keeps
            # any vision constraint already satisfied above intact too.
            # preferred_tool_calling_bean_alias (cost optimization Brew) is
            # None for every caller except use_web routing - see
            # capable_bean()'s own docstring for the override semantics.
            tool_bean = self._bean_registry.capable_bean(
                tool_calling=True, vision=needs_vision, prefer_alias=preferred_tool_calling_bean_alias
            )
            if tool_bean is None:
                raise NoToolCallingBeanError(
                    "This request needs a tool-calling-capable Bean (web search "
                    "or client-supplied tools), but none is configured in beans.yaml."
                )
            if (
                preferred_tool_calling_bean_alias is not None
                and tool_bean.alias != preferred_tool_calling_bean_alias
            ):
                # A preference that stops resolving (renamed, removed,
                # disabled, or lost its capability) must be visible, not a
                # silent, permanent fallback - see capable_bean()'s own
                # "absent, unmatched, or not itself a qualifying candidate"
                # fallthrough, which this makes loud instead of quiet.
                logger.warning(
                    "preferred_tool_calling_bean_alias=%r does not resolve to a "
                    "qualifying Bean (unmatched, unavailable, or lacks the "
                    "required capability) - falling through to cheapest-capable "
                    "Bean %r instead.",
                    preferred_tool_calling_bean_alias,
                    tool_bean.alias,
                )
            if tool_bean.alias != primary_alias:
                # Only a real change of Bean counts as an escalation - a
                # preference that merely confirms the primary Bean already
                # in place must not produce a spurious "escalated from X to
                # X" reason.
                tool_reason = (
                    f"needs_tool_calling: escalated from {primary_alias} to {tool_bean.alias}"
                )
                constraint_reason = (
                    f"{constraint_reason}; {tool_reason}" if constraint_reason else tool_reason
                )
                primary_bean = tool_bean
                primary_alias = tool_bean.alias

        est_cost_usd = estimate_cost_usd(primary_bean, tokens_in, assumed_output_tokens)
        policy_entry_name = f"{task_type}/{_slugify(primary_alias)}"

        return RouteDecision(
            task_type=task_type,
            bean_alias=primary_alias,
            fallback_bean_alias=entry.get("fallback_bean_alias"),
            premium_bean_alias=entry.get("premium_bean_alias"),
            policy_entry=policy_entry_name,
            policy_status=entry.get("status", "default"),
            est_cost_usd=est_cost_usd,
            constraint_reason=constraint_reason,
        )

    def manual_route(
        self,
        task_type: str,
        bean_alias: str,
        needs_vision: bool = False,
        *,
        needs_tool_calling: bool = False,
        tokens_in: int = 0,
        assumed_output_tokens: int = 0,
    ) -> RouteDecision:
        """A human explicitly picked a Bean (Order Box override or
        re-brew dropdown - docs/design/coffee-counter-chat-ui-design.md
        Section 3.2/5.4), bypassing policy selection entirely.
        `policy_entry` becomes "manual/<slug>" instead of a policy path -
        no event-contract schema change, policy_entry was always a
        free-form string. Unlike select_route(), this never silently
        substitutes a different Bean if the requested one is unavailable -
        that would defeat the point of an explicit manual choice - it
        raises instead. The same "never silently substitute" rule applies
        to a vision-needing request manually routed to a non-vision Bean:
        this raises rather than silently switching Beans out from under an
        explicit human choice (unlike select_route()'s policy path, where
        auto-escalating is the whole point)."""

        bean = self._bean_registry.by_alias(bean_alias)
        if not bean.is_available:
            raise RoutingError(
                f"Manually selected Bean {bean_alias!r} is not available "
                f"(status={bean.status!r})."
            )
        if needs_vision and not bean.vision:
            raise RoutingError(
                f"Manually selected Bean {bean_alias!r} does not support vision, "
                "but this request has an image attached. Choose a vision-capable "
                "Bean instead."
            )
        if needs_tool_calling and not bean.tool_calling:
            raise RoutingError(
                f"Manually selected Bean {bean_alias!r} does not support tool "
                "calling, but this request needs it (web search or client-supplied "
                "tools). Choose a tool-calling-capable Bean instead."
            )

        return RouteDecision(
            task_type=task_type,
            bean_alias=bean.alias,
            fallback_bean_alias=None,
            premium_bean_alias=None,
            policy_entry=f"manual/{_slugify(bean.alias)}",
            policy_status="manual_override",
            est_cost_usd=estimate_cost_usd(bean, tokens_in, assumed_output_tokens),
        )

    def select_fallback_route(
        self,
        decision: RouteDecision,
        *,
        tokens_in: int = 0,
        assumed_output_tokens: int = 0,
    ) -> Optional[RouteDecision]:
        if decision.fallback_bean_alias is None:
            return None
        fallback_bean = self._bean_registry.by_alias(decision.fallback_bean_alias)
        if not fallback_bean.is_available:
            return None
        return RouteDecision(
            task_type=decision.task_type,
            bean_alias=fallback_bean.alias,
            fallback_bean_alias=None,
            premium_bean_alias=decision.premium_bean_alias,
            policy_entry=f"{decision.task_type}/{_slugify(fallback_bean.alias)}",
            policy_status=decision.policy_status,
            est_cost_usd=estimate_cost_usd(fallback_bean, tokens_in, assumed_output_tokens),
        )


def estimate_cost_usd(bean, tokens_in: int, assumed_output_tokens: int) -> Optional[float]:
    """Real pre-call cost estimate (spend-cap Brew - replaces the old
    always-0.0-or-None placeholder that never actually estimated a paid
    Bean's cost). tokens_in is the caller's own real estimate of the
    outbound prompt (already computed at every real call site before
    routing, from `len(prompt)//4`/`total_input_chars//4`).
    assumed_output_tokens is deliberately NOT a real prediction - it's the
    client's own `max_tokens` when given (strictly better information than
    a guess), else `settings.spend_cap_assumed_output_tokens` - a
    conservative, overestimate-not-underestimate stand-in for the one
    number that genuinely cannot be known before generation happens.

    This single function now backs both `escalation_cost_cap_usd` (via
    RouteDecision.est_cost_usd/decide_escalation's est_premium_cost_usd)
    and the new per-user/global spend caps - deliberately one estimator,
    not two, so a future bug in cost estimation can't happen twice.
    Returns None only when the Bean has no pricing configured at all -
    should be impossible for an active Bean (see
    router.app.aliases.assert_active_beans_priced), but callers must not
    assume that and should treat None as "cannot verify," not "free."
    """

    if bean.price_per_1k_input_usd is None or bean.price_per_1k_output_usd is None:
        return None
    return round(
        (tokens_in / 1000) * bean.price_per_1k_input_usd
        + (assumed_output_tokens / 1000) * bean.price_per_1k_output_usd,
        6,
    )


def _slugify(alias: str) -> str:
    return alias.lower().replace(" ", "-")
