"""Policy loader and Bean selection for the Coffee Core Router.

Loads router/config/routing_policy.yaml (generated by tools/generate_policy.py
- never hand-edited) and selects a primary/fallback Bean per classified
task_type. Every routing decision records which policy entry justified it
(Requirement 4).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

from router.app.aliases import BeanRegistry

DEFAULT_ROUTING_POLICY_PATH = Path(__file__).resolve().parent.parent / "config" / "routing_policy.yaml"


class RoutingError(Exception):
    """Raised when a route cannot be resolved to an available Bean."""


@dataclass(frozen=True)
class RouteDecision:
    task_type: str
    bean_alias: str
    fallback_bean_alias: Optional[str]
    premium_bean_alias: Optional[str]
    policy_entry: str
    policy_status: str
    est_cost_usd: Optional[float]


class RoutingPolicy:
    def __init__(self, policy_data: Dict[str, Any], bean_registry: BeanRegistry):
        self._policy_data = policy_data
        self._bean_registry = bean_registry

    @classmethod
    def from_yaml(
        cls,
        path: Path = DEFAULT_ROUTING_POLICY_PATH,
        bean_registry: Optional[BeanRegistry] = None,
    ) -> "RoutingPolicy":
        with open(path, "r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        return cls(data, bean_registry or BeanRegistry.from_yaml())

    def entry_for_task_type(self, task_type: str) -> Dict[str, Any]:
        task_types = self._policy_data.get("task_types", {})
        entry = task_types.get(task_type)
        if entry is None:
            # Unknown task_type (e.g. classifier returned something the
            # policy has never seen): treat exactly like "default" rather
            # than raising, matching Requirement 4's stated fallback
            # behavior for thin/missing evidence.
            return {
                "status": "default",
                "primary_bean_alias": self._house_blend_default_alias(),
                "fallback_bean_alias": None,
                "premium_bean_alias": None,
                "evidence": [],
                "reason": f"Unknown task_type={task_type!r}; no policy entry exists.",
            }
        return entry

    def _house_blend_default_alias(self) -> str:
        default_bean = self._bean_registry.by_role("default")
        if default_bean is None:
            raise RoutingError("No default Bean is configured in beans.yaml.")
        return default_bean.alias

    def select_route(self, task_type: str) -> RouteDecision:
        entry = self.entry_for_task_type(task_type)
        primary_alias = entry.get("primary_bean_alias") or self._house_blend_default_alias()
        primary_bean = self._bean_registry.by_alias(primary_alias)

        if not primary_bean.is_available:
            # Never silently substitute a different role for an unavailable
            # Bean (Coffee Constitution Article 1: "must never represent
            # unverified output as certain fact" extends to routing
            # honesty). Fall back to the configured House Blend default.
            fallback_default_alias = self._house_blend_default_alias()
            primary_bean = self._bean_registry.by_alias(fallback_default_alias)
            primary_alias = fallback_default_alias

        est_cost_usd = _estimate_cost_usd(primary_bean)
        policy_entry_name = f"{task_type}/{_slugify(primary_alias)}"

        return RouteDecision(
            task_type=task_type,
            bean_alias=primary_alias,
            fallback_bean_alias=entry.get("fallback_bean_alias"),
            premium_bean_alias=entry.get("premium_bean_alias"),
            policy_entry=policy_entry_name,
            policy_status=entry.get("status", "default"),
            est_cost_usd=est_cost_usd,
        )

    def select_fallback_route(self, decision: RouteDecision) -> Optional[RouteDecision]:
        if decision.fallback_bean_alias is None:
            return None
        fallback_bean = self._bean_registry.by_alias(decision.fallback_bean_alias)
        if not fallback_bean.is_available:
            return None
        return RouteDecision(
            task_type=decision.task_type,
            bean_alias=fallback_bean.alias,
            fallback_bean_alias=None,
            premium_bean_alias=decision.premium_bean_alias,
            policy_entry=f"{decision.task_type}/{_slugify(fallback_bean.alias)}",
            policy_status=decision.policy_status,
            est_cost_usd=_estimate_cost_usd(fallback_bean),
        )


def _estimate_cost_usd(bean) -> Optional[float]:
    if bean.price_per_1k_input_usd is None or bean.price_per_1k_output_usd is None:
        return None
    return 0.0 if (bean.price_per_1k_input_usd == 0.0 and bean.price_per_1k_output_usd == 0.0) else None


def _slugify(alias: str) -> str:
    return alias.lower().replace(" ", "-")
